// Content script for YouTube - extracts transcript directly from the page
(function() {
  'use strict';

  // Extract video ID from URL
  function getVideoId() {
    const urlParams = new URLSearchParams(window.location.search);
    return urlParams.get('v');
  }

  // Extract ytInitialPlayerResponse from the page
  function getPlayerResponse() {
    // Try multiple methods to get the player response
    
    // Method 1: Direct window access
    if (window.ytInitialPlayerResponse) {
      return window.ytInitialPlayerResponse;
    }
    
    // Method 2: Try ytInitialData
    if (window.ytInitialData?.contents?.twoColumnWatchNextResults?.results?.results?.contents) {
      const playerResponse = window.ytInitialData?.playerResponse;
      if (playerResponse) return playerResponse;
    }
    
    // Method 3: Parse from script tags - improved regex
    const scripts = document.querySelectorAll('script');
    for (const script of scripts) {
      const text = script.textContent || script.innerHTML || '';
      if (text.includes('ytInitialPlayerResponse')) {
        // Try multiple regex patterns
        const patterns = [
          /ytInitialPlayerResponse\s*=\s*({.+?});/s,
          /"ytInitialPlayerResponse"\s*:\s*({.+?})/s,
          /ytInitialPlayerResponse\s*=\s*({[\s\S]+?});\s*(?:var|let|const|$)/,
          /ytInitialPlayerResponse\s*=\s*({[\s\S]+?});/
        ];
        
        for (const pattern of patterns) {
          const match = text.match(pattern);
          if (match && match[1]) {
            try {
              const parsed = JSON.parse(match[1]);
              if (parsed && parsed.videoDetails) {
                return parsed;
              }
            } catch (e) {
              // Try to fix common JSON issues
              try {
                const fixed = match[1]
                  .replace(/,\s*}/g, '}')
                  .replace(/,\s*]/g, ']');
                const parsed = JSON.parse(fixed);
                if (parsed && parsed.videoDetails) {
                  return parsed;
                }
              } catch (e2) {
                // Continue to next pattern
              }
            }
          }
        }
      }
    }
    
    // Method 4: Try to find in ytcfg
    if (window.ytcfg && window.ytcfg.data_) {
      const data = window.ytcfg.data_;
      if (data.INNERTUBE_CONTEXT && data.INNERTUBE_CONTEXT.client) {
        // Try to find player response in various places
        const playerResponse = data.PLAYER_RESPONSE || data.playerResponse;
        if (playerResponse) return playerResponse;
      }
    }
    
    return null;
  }

  // Get caption track URL from player response
  function getCaptionTrackUrl(playerResponse, preferredLang = 'fr') {
    try {
      const captions = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
      if (!captions || captions.length === 0) {
        return null;
      }

      // Try to find preferred language first
      let track = captions.find(t => t.languageCode === preferredLang);
      
      // Fallback to English
      if (!track) {
        track = captions.find(t => t.languageCode === 'en');
      }
      
      // Fallback to first available
      if (!track) {
        track = captions[0];
      }

      return {
        url: track.baseUrl,
        language: track.languageCode,
        name: track.name?.simpleText || track.languageCode,
        isAutoGenerated: track.kind === 'asr'
      };
    } catch (e) {
      console.error('Failed to get caption track:', e);
      return null;
    }
  }

  // Fetch and parse transcript from caption URL
  async function fetchTranscript(captionUrl) {
    try {
      // Add format parameter to get JSON instead of XML
      const url = new URL(captionUrl);
      url.searchParams.set('fmt', 'json3');
      
      const response = await fetch(url.toString());
      if (!response.ok) {
        throw new Error(`Failed to fetch transcript: ${response.status}`);
      }

      const data = await response.json();
      
      // Parse the transcript events
      const segments = [];
      for (const event of data.events || []) {
        if (event.segs) {
          const text = event.segs.map(seg => seg.utf8).join('').trim();
          if (text) {
            segments.push({
              text: text,
              start: Math.floor((event.tStartMs || 0) / 1000),
              duration: Math.floor((event.dDurationMs || 0) / 1000)
            });
          }
        }
      }

      return segments;
    } catch (e) {
      console.error('Failed to fetch transcript:', e);
      return null;
    }
  }

  // Format transcript segments into readable text
  function formatTranscript(segments) {
    if (!segments || segments.length === 0) return null;

    let formatted = '';
    let currentMinute = -1;

    for (const segment of segments) {
      const minutes = Math.floor(segment.start / 60);
      const seconds = segment.start % 60;

      // Add timestamp every minute
      if (minutes !== currentMinute) {
        currentMinute = minutes;
        const timestamp = `[${minutes}:${seconds.toString().padStart(2, '0')}]`;
        formatted += `\n\n${timestamp} `;
      }

      formatted += segment.text + ' ';
    }

    return formatted.trim();
  }

  // Get video metadata from the page
  function getVideoMetadata() {
    const playerResponse = getPlayerResponse();
    
    if (playerResponse?.videoDetails) {
      const details = playerResponse.videoDetails;
      return {
        videoId: details.videoId,
        title: details.title,
        author: details.author,
        channelId: details.channelId,
        lengthSeconds: parseInt(details.lengthSeconds) || 0,
        viewCount: parseInt(details.viewCount) || 0,
        description: details.shortDescription,
        thumbnail: details.thumbnail?.thumbnails?.slice(-1)[0]?.url,
        isLive: details.isLiveContent || false
      };
    }

    // Fallback to DOM parsing
    return {
      videoId: getVideoId(),
      title: document.querySelector('h1.ytd-video-primary-info-renderer')?.textContent?.trim() 
             || document.querySelector('meta[name="title"]')?.content,
      author: document.querySelector('#owner-name a')?.textContent?.trim(),
      thumbnail: document.querySelector('meta[property="og:image"]')?.content,
      description: document.querySelector('meta[name="description"]')?.content
    };
  }

  // Main function to extract all YouTube data
  async function extractYouTubeData() {
    const videoId = getVideoId();
    if (!videoId) {
      return { error: 'Not a video page' };
    }

    // Wait a bit for page to fully load if needed
    let playerResponse = getPlayerResponse();
    if (!playerResponse) {
      // Wait and retry
      await new Promise(resolve => setTimeout(resolve, 500));
      playerResponse = getPlayerResponse();
    }

    const metadata = getVideoMetadata();
    
    // Get caption track
    const captionTrack = getCaptionTrackUrl(playerResponse);
    
    let transcript = null;
    let transcriptSource = 'none';
    let transcriptError = null;

    if (captionTrack) {
      try {
        const segments = await fetchTranscript(captionTrack.url);
        if (segments && segments.length > 0) {
          transcript = formatTranscript(segments);
          transcriptSource = captionTrack.isAutoGenerated ? 'auto-generated' : 'manual';
        } else {
          transcriptError = 'No transcript segments found';
        }
      } catch (error) {
        transcriptError = error.message || 'Failed to fetch transcript';
        console.error('Transcript fetch error:', error);
      }
    } else {
      transcriptError = playerResponse ? 'No captions available for this video' : 'Could not access video data';
    }

    return {
      videoId,
      url: window.location.href,
      metadata,
      transcript,
      transcriptSource,
      captionLanguage: captionTrack?.language || null,
      hasFullTranscript: transcript !== null && transcript.length > 100,
      transcriptError: transcriptError || null,
      extractedAt: new Date().toISOString()
    };
  }

  // Listen for messages from popup/background
  chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.action === 'extractYouTubeData') {
      extractYouTubeData().then(data => {
        sendResponse(data);
      }).catch(error => {
        sendResponse({ error: error.message });
      });
      return true; // Keep channel open for async response
    }

    if (request.action === 'getVideoId') {
      sendResponse({ videoId: getVideoId() });
      return true;
    }

    if (request.action === 'ping') {
      sendResponse({ status: 'ok', isYouTube: true });
      return true;
    }
  });

  // Notify that content script is loaded
  console.log('[Recap Extension] YouTube content script loaded');
})();

