// Content script for YouTube - extracts transcript directly from the page
(function() {
  'use strict';

  // Extract video ID from URL
  function getVideoId() {
    const urlParams = new URLSearchParams(window.location.search);
    return urlParams.get('v');
  }

  // Extract ytInitialPlayerResponse from the page
  function getPlayerResponse() {
    // Try to get from window object (may be blocked by CSP)
    if (window.ytInitialPlayerResponse) {
      return window.ytInitialPlayerResponse;
    }
    
    // Fallback: parse from script tags
    const scripts = document.querySelectorAll('script');
    for (const script of scripts) {
      const text = script.textContent || '';
      if (text.includes('ytInitialPlayerResponse')) {
        const match = text.match(/ytInitialPlayerResponse\s*=\s*({.+?});/);
        if (match) {
          try {
            return JSON.parse(match[1]);
          } catch (e) {
            console.error('Failed to parse ytInitialPlayerResponse:', e);
          }
        }
      }
    }
    return null;
  }

  // Get caption track URL from player response
  function getCaptionTrackUrl(playerResponse, preferredLang = 'fr') {
    try {
      const captions = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
      if (!captions || captions.length === 0) {
        return null;
      }

      // Try to find preferred language first
      let track = captions.find(t => t.languageCode === preferredLang);
      
      // Fallback to English
      if (!track) {
        track = captions.find(t => t.languageCode === 'en');
      }
      
      // Fallback to first available
      if (!track) {
        track = captions[0];
      }

      return {
        url: track.baseUrl,
        language: track.languageCode,
        name: track.name?.simpleText || track.languageCode,
        isAutoGenerated: track.kind === 'asr'
      };
    } catch (e) {
      console.error('Failed to get caption track:', e);
      return null;
    }
  }

  // Fetch and parse transcript from caption URL
  async function fetchTranscript(captionUrl) {
    try {
      // Add format parameter to get JSON instead of XML
      const url = new URL(captionUrl);
      url.searchParams.set('fmt', 'json3');
      
      const response = await fetch(url.toString());
      if (!response.ok) {
        throw new Error(`Failed to fetch transcript: ${response.status}`);
      }

      const data = await response.json();
      
      // Parse the transcript events
      const segments = [];
      for (const event of data.events || []) {
        if (event.segs) {
          const text = event.segs.map(seg => seg.utf8).join('').trim();
          if (text) {
            segments.push({
              text: text,
              start: Math.floor((event.tStartMs || 0) / 1000),
              duration: Math.floor((event.dDurationMs || 0) / 1000)
            });
          }
        }
      }

      return segments;
    } catch (e) {
      console.error('Failed to fetch transcript:', e);
      return null;
    }
  }

  // Format transcript segments into readable text
  function formatTranscript(segments) {
    if (!segments || segments.length === 0) return null;

    let formatted = '';
    let currentMinute = -1;

    for (const segment of segments) {
      const minutes = Math.floor(segment.start / 60);
      const seconds = segment.start % 60;

      // Add timestamp every minute
      if (minutes !== currentMinute) {
        currentMinute = minutes;
        const timestamp = `[${minutes}:${seconds.toString().padStart(2, '0')}]`;
        formatted += `\n\n${timestamp} `;
      }

      formatted += segment.text + ' ';
    }

    return formatted.trim();
  }

  // Get video metadata from the page
  function getVideoMetadata() {
    const playerResponse = getPlayerResponse();
    
    if (playerResponse?.videoDetails) {
      const details = playerResponse.videoDetails;
      return {
        videoId: details.videoId,
        title: details.title,
        author: details.author,
        channelId: details.channelId,
        lengthSeconds: parseInt(details.lengthSeconds) || 0,
        viewCount: parseInt(details.viewCount) || 0,
        description: details.shortDescription,
        thumbnail: details.thumbnail?.thumbnails?.slice(-1)[0]?.url,
        isLive: details.isLiveContent || false
      };
    }

    // Fallback to DOM parsing
    return {
      videoId: getVideoId(),
      title: document.querySelector('h1.ytd-video-primary-info-renderer')?.textContent?.trim() 
             || document.querySelector('meta[name="title"]')?.content,
      author: document.querySelector('#owner-name a')?.textContent?.trim(),
      thumbnail: document.querySelector('meta[property="og:image"]')?.content,
      description: document.querySelector('meta[name="description"]')?.content
    };
  }

  // Main function to extract all YouTube data
  async function extractYouTubeData() {
    const videoId = getVideoId();
    if (!videoId) {
      return { error: 'Not a video page' };
    }

    const playerResponse = getPlayerResponse();
    const metadata = getVideoMetadata();
    
    // Get caption track
    const captionTrack = getCaptionTrackUrl(playerResponse);
    
    let transcript = null;
    let transcriptSource = 'none';

    if (captionTrack) {
      const segments = await fetchTranscript(captionTrack.url);
      if (segments && segments.length > 0) {
        transcript = formatTranscript(segments);
        transcriptSource = captionTrack.isAutoGenerated ? 'auto-generated' : 'manual';
      }
    }

    return {
      videoId,
      url: window.location.href,
      metadata,
      transcript,
      transcriptSource,
      captionLanguage: captionTrack?.language || null,
      hasFullTranscript: transcript !== null && transcript.length > 100,
      extractedAt: new Date().toISOString()
    };
  }

  // Listen for messages from popup/background
  chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.action === 'extractYouTubeData') {
      extractYouTubeData().then(data => {
        sendResponse(data);
      }).catch(error => {
        sendResponse({ error: error.message });
      });
      return true; // Keep channel open for async response
    }

    if (request.action === 'getVideoId') {
      sendResponse({ videoId: getVideoId() });
      return true;
    }

    if (request.action === 'ping') {
      sendResponse({ status: 'ok', isYouTube: true });
      return true;
    }
  });

  // Notify that content script is loaded
  console.log('[Recap Extension] YouTube content script loaded');
})();
